baseURL = 'https://seddonshen.github.io'
title = 'Shidong Shen'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = 'github.com/geekifan/zero-academic-page'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Shidong Shen'

    [languages.en.params]
      author = "Shidong Shen"
      description = "Master Student at [ISCAS, CAS](https://www.iscas.ac.cn/) and [UCAS](https://www.ucas.ac.cn/). Focusing on Formal Verification and LLM4SE."
      motto = "Stay Hungry, Stay Foolish."
    
    [[languages.en.menu.main]]
      name = 'About Me'
      url = '#about-me'
      weight = 1
    [[languages.en.menu.main]]
      name = 'News'
      url = '#news'
      weight = 2
    [[languages.en.menu.main]]
      name = 'Publications'
      url = '#publications'
      weight = 3
    [[languages.en.menu.main]]
      name = 'Projects'
      url = '#projects'
      weight = 4
    [[languages.en.menu.main]]
      name = 'Honors and Awards'
      url = '#honors-and-awards'
      weight = 5
    [[languages.en.menu.main]]
      name = 'Educations'
      url = '#educations'
      weight = 6

[params]
  profilePicture = "images/profile.jpg"
  enableDarkMode = true
  
  [[params.social]]
    name = "github"
    url = "https://github.com/SeddonShen"
    icon = "fab fa-github"
  [[params.social]]
    name = "email"
    url = "mailto:shensd@ios.ac.cn"
    icon = "fas fa-envelope"
  [[params.social]]
    name = "orcid"
    url = "https://orcid.org/0009-0000-0369-021X"
    icon = "fab fa-orcid"
[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
